# Autogenerated wrapper script for RE2_jll for x86_64-apple-darwin
export libre2

JLLWrappers.@generate_wrapper_header("RE2")
JLLWrappers.@declare_library_product(libre2, "@rpath/libre2.9.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libre2,
        "lib/libre2.9.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
